version: 0.2
env:
  variables:
    STACKNAME: "security-fairy"
    DEPLOY_BUCKET: "1s-potato-not-west"

phases:
  pre_build:
    commands:
      - ls -lha
      - TIME=$(date -d "30 min ago" +"%FT%T.0Z")       
      - sudo apt-get update
      - sudo apt-get -y install unzip jq
      - sudo pip install --upgrade pip
      - sudo pip install requests

  build:
    commands:
      - aws cloudformation package --template-file ./template.yaml --output-template-file ./template-output.yaml --s3-bucket ${DEPLOY_BUCKET}
      - >
        aws cloudformation deploy --template-file ./template-output.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --stack-name $STACKNAME \
            --no-fail-on-empty-changeset \
            --parameter-overrides file://parameters.json || #\
            # --tags file://tags.json || 
            $(printf "aws cloudformation describe-stack-events \
                    --stack-name %s \
                    --output table \
                    --query 'StackEvents[?Timestamp >= \`%s\`].[Timestamp,ResourceType,LogicalResourceId,ResourceStatus,ResourceStatusReason]'" $STACKNAME $TIME | sh && exit 1)
  post_build:
    commands:
      # Capture CloudFormation outputs in ./tests/cloudformation-outputs.json
      - aws cloudformation describe-stacks --stack-name ${STACKNAME} --query 'Stacks[*].Outputs' | jq '.[]' > cloudformation-outputs.json

