AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a security auditing tool
Parameters:
  CloudTrailS3Bucket:
    Type: String
    Description: This is the bucket where your cloudtrail logs feed into
  SNSEmail:
    Type: String
    Description: The email where SNS notifications will be sent
Resources:
  SecurityFairySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SecurityFairy
      Subscription:
      - Endpoint:
          Ref: SNSEmail
        Protocol: email
      TopicName: security_fairy_topic
  SecurityFairyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: security-fairy-bucket-${AWS::Region}-${AWS::AccountId}
  SecurityFairyDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: execution_id
        AttributeType: S
      - AttributeName: entity_arn
        AttributeType: S
      KeySchema:
      - AttributeName: execution_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
      - IndexName: entity_arn
        KeySchema:
        - AttributeName: entity_arn
          KeyType: HASH
        Projection:
          NonKeyAttributes:
          - entity_arn
          ProjectionType: INCLUDE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      TableName: security_fairy_dynamodb_table
  SecurityFairyApprovalActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      Name: security_fairy_approval_activity
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/service-role/StatesExecutionRole-${AWS::Region}
      DefinitionString:
        Fn::Sub: "{\n  \"StartAt\": \"InjectVariables\",\n  \"States\": {\n    \"\
          InjectVariables\": {\n    \"Type\": \"Task\",\n    \"Resource\": \"arn:aws:lambda:us-east-1:842337631775:function:security_fairy_variable_injection\"\
          ,\n    \"Next\": \"QueryAthena\"\n    },\n    \"QueryAthena\": {\n     \
          \ \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:lambda:us-east-1:842337631775:function:security_fairy_athena_query\"\
          ,\n      \"Next\": \"WaitForQuery\"\n    },\n    \"WaitForQuery\": {\n \
          \     \"Type\": \"Wait\",\n      \"Seconds\": 60,\n      \"Next\": \"BuildPolicy\"\
          \n    },\n    \"BuildPolicy\": {\n      \"Type\": \"Task\",\n      \"Resource\"\
          : \"arn:aws:lambda:us-east-1:842337631775:function:security_fairy_revised_policy_generator\"\
          ,\n      \"Retry\": [{\n        \"ErrorEquals\": [\n          \"States.ALL\"\
          \n        ],\n        \"IntervalSeconds\": 60,\n        \"MaxAttempts\"\
          : 3,\n        \"BackoffRate\": 1.5\n      }],\n      \"Next\": \"QueryFinish?\"\
          \n    },\n    \"QueryFinish?\": {\n      \"Type\" : \"Choice\",\n      \"\
          Choices\": [\n        {\n          \"Variable\": \"$.query_state\",\n  \
          \        \"StringEquals\": \"StillRunning\",\n          \"Next\": \"WaitForQuery\"\
          \n        }],\n        \"Default\": \"PromptForApproval\"\n    },\n    \"\
          PromptForApproval\": {\n      \"Type\": \"Parallel\",\n      \"End\": true,\n\
          \      \"Branches\": [{\n          \"StartAt\": \"Approval\",\n        \
          \  \"States\": {\n            \"Approval\": {\n              \"Type\": \"\
          Task\",\n              \"Resource\": \"arn:aws:states:us-east-1:842337631775:activity:security_fairy_approval_activity\"\
          ,\n              \"Catch\": [{\n                \"ErrorEquals\": [\"States.TaskFailed\"\
          , \"States.Timeout\"],\n                \"Next\": \"PolicyDenial\"\n   \
          \           }],\n              \"Next\": \"PolicyApply\"\n            },\n\
          \            \"PolicyApply\": {\n              \"Type\": \"Task\",\n   \
          \           \"Resource\": \"arn:aws:lambda:us-east-1:842337631775:function:security_fairy_revised_policy_approve\"\
          ,\n              \"End\": true\n            },\n            \"PolicyDenial\"\
          : {\n              \"Type\": \"Task\",\n              \"Resource\": \"arn:aws:lambda:us-east-1:842337631775:function:security_fairy_revised_policy_deny\"\
          ,\n              \"End\": true\n            }\n          }\n        },\n\
          \        {\n          \"StartAt\": \"WaitForCode\",\n          \"States\"\
          : {\n            \"WaitForCode\": {\n              \"Type\": \"Wait\",\n\
          \              \"Seconds\": 3,\n              \"Next\": \"GenerateCode\"\
          \n            },\n            \"GenerateCode\": {\n              \"Type\"\
          : \"Task\",\n              \"Resource\": \"arn:aws:lambda:us-east-1:842337631775:function:security_fairy_get_task_token\"\
          ,\n\n              \"Next\": \"SendApprovalRequest\"\n            },\n \
          \           \"SendApprovalRequest\": {\n              \"Type\": \"Task\"\
          ,\n              \"Resource\": \"arn:aws:lambda:us-east-1:842337631775:function:security_fairy_email_approval_request\"\
          ,\n              \"End\": true\n            }\n          }\n        }\n\
          \      ]\n    }\n  }\n}"
  SecurityFairyApiEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_api_endpoint
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: api_endpoint.lambda_handler
      MemorySize: 128
      Policies:
      - AdministratorAccess
      Runtime: python2.7
      Timeout: 30
      Environment:
        Variables:
          state_machine:
            Ref: StateMachine
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /start
            Method: GET
        PostApi:
          Type: Api
          Properties:
            Path: /start
            Method: POST
  SecurityFairyRevertApiEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_api_revert
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: revert.lambda_handler
      MemorySize: 128
      Policies:
      - AdministratorAccess
      Runtime: python2.7
      Timeout: 30
      Environment:
        Variables:
          state_machine:
            Ref: StateMachine
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /revert
            Method: GET
        PostApi:
          Type: Api
          Properties:
            Path: /revert
            Method: POST
  SecurityFairyVariableInjection:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_variable_injection
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: This function queries Athena to determine permissions
      Handler: variable_injection.lambda_handler
      MemorySize: 128
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      Runtime: python2.7
      Timeout: 30
      Environment:
        Variables:
          sns_arn:
            Ref: SecurityFairySNSTopic
          dynamodb_table:
            Ref: SecurityFairyDynamoDB
          activity_arn:
            Fn::Sub: arn:aws:states:${AWS::Region}:${AWS::AccountId}:activity:security_fairy_approval_activity
          s3_bucket:
            Ref: SecurityFairyS3Bucket
          api_endpoint:
            Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  SecurityFairyAthenaQuery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_athena_query
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: This function queries Athena to determine permissions
      Handler: athena_query.lambda_handler
      MemorySize: 128
      Policies:
      - AmazonAthenaFullAccess
      - AmazonS3FullAccess
      Runtime: python3.6
      Timeout: 30
  SecurityFairyTableCreation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_build_cloudtrail_table
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: This function builds the required cloudtrail table in Athena
      Handler: build_cloudtrail_table.lambda_handler
      MemorySize: 128
      Policies:
      - AmazonAthenaFullAccess
      - AmazonS3FullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      Runtime: python3.6
      Timeout: 300
      Environment:
        Variables:
          aws_account:
            Ref: AWS::AccountId
          cloudtrail_bucket:
            Ref: CloudTrailS3Bucket
          security_fairy_bucket:
            Ref: SecurityFairyS3Bucket
  LaunchSecurityFairyTableCreation:
    Type: AWS::CloudFormation::CustomResource
    DeletionPolicy: Retain
    DependsOn: SecurityFairyTableCreation
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - SecurityFairyTableCreation
        - Arn
  SecurityFairyPolicyGenerator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_revised_policy_generator
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: revised_policy_generator.lambda_handler
      MemorySize: 128
      Policies:
      - IAMReadOnlyAccess
      - AmazonAthenaFullAccess
      - AmazonDynamoDBFullAccess
      - AmazonS3ReadOnlyAccess
      Runtime: python2.7
      Timeout: 30
  SecurityFairyEmailApproval:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_email_approval_request
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: email_approval_request.lambda_handler
      MemorySize: 128
      Policies:
      - AmazonSNSFullAccess
      - AWSStepFunctionsFullAccess
      Runtime: python2.7
      Timeout: 30
  SecurityFairyApiApproval:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_api_approval
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: api_approval.lambda_handler
      MemorySize: 512
      Runtime: python2.7
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSStepFunctionsFullAccess
      Environment:
        Variables:
          dynamodb_table:
            Ref: SecurityFairyDynamoDB
      Events:
        ApprovalGetApi:
          Type: Api
          Properties:
            Path: /{approval}
            Method: GET
        ApprovalPostApi:
          Type: Api
          Properties:
            Path: /{approval}
            Method: POST
  SecurityFairyApprovePolicy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_revised_policy_approve
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: revised_policy_approve.lambda_handler
      MemorySize: 128
      Policies:
      - IAMReadOnlyAccess
      - AmazonDynamoDBFullAccess
      - AdministratorAccess
      - AWSStepFunctionsFullAccess
      Runtime: python2.7
      Timeout: 30
      Environment:
        Variables:
          dynamodb_table:
            Ref: SecurityFairyDynamoDB
  SecurityFairyDenyPolicy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_revised_policy_deny
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: revised_policy_deny.lambda_handler
      MemorySize: 128
      Policies:
      - AmazonDynamoDBFullAccess
      Runtime: python2.7
      Timeout: 30
      Environment:
        Variables:
          dynamodb_table:
            Ref: SecurityFairyDynamoDB
  SecurityFairyGetTaskToken:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_get_task_token
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: get_task_token.lambda_handler
      MemorySize: 128
      Runtime: python2.7
      Timeout: 30
      Policies:
      - AWSStepFunctionsFullAccess
  SecurityFairyCloudTrailAutoPartition:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: security_fairy_partition_cloudtrail_bucket
      CodeUri: s3://1s-potato-not-west/3739138278f75d0ab9c7892030a70637
      Description: ''
      Handler: partition_cloudtrail_bucket.lambda_handler
      MemorySize: 128
      Policies:
      - AdministratorAccess
      Runtime: python3.6
      Timeout: 30
      Environment:
        Variables:
          aws_account:
            Ref: AWS::AccountId
          cloudtrail_bucket:
            Ref: CloudTrailS3Bucket
          security_fairy_bucket:
            Ref: SecurityFairyS3Bucket
      Events:
        DailyRun:
          Type: Schedule
          Properties:
            Schedule: cron(10 0 * * ? *)
Outputs:
  ApiEndpoint:
    Description: Security Fairy Invocation Endpoint
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start
